set_languages("c11", "cxx17")
add_rules("mode.debug")

target("Kaleidoscope")
    add_cxxflags("-g -v")
    set_targetdir("build")
    set_kind("binary")
    add_files("Kaleidoscope/**.cc")
    add_rpathdirs("/usr/lib/llvm-14/lib")
    add_deps("libLLVM-14.so")
    add_defines("__STDC_LIMIT_MACROS")
    add_defines("__STDC_CONSTANT_MACROS")
    add_defines("__STDC_FORMAT_MACROS")
    add_defines("_GNU_SOURCE")
